/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaland;

import com.raven.datechooser.SelectedDate;
import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Date;
/**
 *
 * @author Orhan UZEL
 */
public class CalismaEkrani extends javax.swing.JFrame {
int idm;
public int idAl(int id){
    idm=id;
    return id;
}
    public CalismaEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalismaEkraniPaneli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCalismaGunSayisi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCalismaSaati = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        butonCalismayaBasla = new javax.swing.JButton();
        dateChooser1 = new com.raven.datechooser.DateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CalismaEkraniPaneli.setBackground(new java.awt.Color(255, 204, 204));
        CalismaEkraniPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Çalışma Bitiş Tarihi");
        CalismaEkraniPaneli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));
        CalismaEkraniPaneli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 163, -1, -1));

        txtCalismaGunSayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalismaGunSayisiActionPerformed(evt);
            }
        });
        CalismaEkraniPaneli.add(txtCalismaGunSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 71, 30));

        jLabel3.setText("Çalışma Gün Sayısı");
        CalismaEkraniPaneli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, 30));
        CalismaEkraniPaneli.add(txtCalismaSaati, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 71, 30));

        jLabel4.setText("Çalışma Saati");
        CalismaEkraniPaneli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 100, 30));

        butonCalismayaBasla.setText("Çalışmaya Başla");
        butonCalismayaBasla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonCalismayaBaslaActionPerformed(evt);
            }
        });
        CalismaEkraniPaneli.add(butonCalismayaBasla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));
        CalismaEkraniPaneli.add(dateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalismaEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalismaEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalismaGunSayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalismaGunSayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalismaGunSayisiActionPerformed

    private void butonCalismayaBaslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonCalismayaBaslaActionPerformed
  //String calisma_ekleme_sorgusu = "INSERT INTO kullanici" + " (kullanici_adi,sifre,tarih) VALUES " + " (?,?,?);";//current_date 3. soru işareti yerine 
  String calisma_ekleme_sorgusu = "INSERT INTO kullanici_calisma_bilgileri" + " (kullanici_calisma_baslangici,kullanici_calisma_bitisi,kullanici_calisma_gun_sayisi,kullanici_calisma_saatleri,kullanici_id) VALUES " + " (CURRENT_DATE,?,?,?,?);";   
  veritabani vt=new veritabani();
  
        //Date bitisTarihi=new Date();
        SelectedDate bitisTarihi=dateChooser1.getSelectedDate();
        int bitisGunu=bitisTarihi.getDay();
       int bitisAyi= bitisTarihi.getMonth();
       int bitisYil= bitisTarihi.getYear();
      OyunEkrani oyunEkrani=new OyunEkrani();/////kaldırılıbabilir kısımlardan olabilir 
       for(int i=0;i<4;i++){
            for(int j=0;j<4;j++){
                System.out.print(oyunEkrani.oyunAlani[i][j]);
            }
            System.out.println();
        }
     // oyunEkrani.idAl(idm)
      int kullanici_id= oyunEkrani.idm;
       // int bitisGunu=Integer.parseInt( txtCalismaBitisGun.getText());
       // int bitisAyi=Integer.parseInt( txtCalismaBitisAy.getText());
       // int bitisYil=Integer.parseInt( txtCalismaBitisYil.getText());
        String calismaGunu=txtCalismaGunSayisi.getText();
        int icalismaGunu=Integer.parseInt(calismaGunu);
        String calismasaati=txtCalismaSaati.getText();
        int icalismasaati=Integer.parseInt(calismasaati);
       // txtCalismaBitis.get
                
        try {
            // Connection con=  (Connection) vt.yaps();
            // vt=con.createStatement();
            vt.insertRecord(calisma_ekleme_sorgusu,bitisGunu,bitisAyi,bitisYil,icalismasaati,icalismaGunu,kullanici_id);
        } catch (SQLException ex) {
            Logger.getLogger(CalismaEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        try { 
            String url = "jdbc:postgresql://localhost:5432/"; 
            Connection conn = (Connection) DriverManager.getConnection(url,"postgres","PASSWORD"); 
            Statement st = conn.createStatement(); 
            st.executeUpdate("INSERT INTO Customers " + 
                "VALUES (1001, 'Simpson', 'Mr.', 'Springfield', 2001)"); 
            st.executeUpdate("INSERT INTO Customers " + 
                "VALUES (1002, 'McBeal', 'Ms.', 'Boston', 2004)"); 
            st.executeUpdate("INSERT INTO Customers " + 
                "VALUES (1003, 'Flinstone', 'Mr.', 'Bedrock', 2003)"); 
            st.executeUpdate("INSERT INTO Customers " + 
                "VALUES (1004, 'Cramden', 'Mr.', 'New York', 2001)");

            conn.close(); 
        } catch (Exception e) { 
            System.err.println("Got an exception! "); 
            System.err.println(e.getMessage()); 
        } 
        */
       //  String zamanSorgum="INSER INTO kullanici_calisma_bilgileri values (?,?,?,?,?,?)";        
       /*
       String zamanSorgum="INSERT INTO kullanici values(?,?,?)"; 
           ResultSet kullanici_bilgilerim2 = veritabani.yap();
			 kullanici_bilgilerim2 = veritabani.sorgula(zamanSorgum);//resultset üst taraftaydı  
                      // veritabani.sorgula(zamanSorgum).statement.executeUpdate("INSERT INTO Customers " + "VALUES (1002, 'McBeal', 'Ms.', 'Boston', 2004)");
        try {
            PreparedStatement ps=veritabani.conn.prepareStatement(zamanSorgum);
           // ps.setString(1,Integer.parseInt(txtCalismaSaati.getText()) );
         //   ps.setInt(1,Integer.parseInt(txtCalismaSaati.getText()));
            ps.setString(2,txtCalismaBitisGun.getText() );
            ps.setString(3,txtCalismaGunSayisi.getText() );
           
        
        } catch (SQLException ex) {
            Logger.getLogger(MagazaEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        
    }//GEN-LAST:event_butonCalismayaBaslaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalismaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalismaEkraniPaneli;
    private javax.swing.JButton butonCalismayaBasla;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCalismaGunSayisi;
    private javax.swing.JTextField txtCalismaSaati;
    // End of variables declaration//GEN-END:variables
}
