/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaland;

import javax.swing.JOptionPane;

/**
 *
 * @author Orhan UZEL
 */
public class EmlakEkrani extends javax.swing.JFrame {
int kurulacakIsletmeTuruBelirlendi=0;
    /**
     * Creates new form EmlakEkrani
     */
    public EmlakEkrani() {
        initComponents();
        satinAlmaPaneli.setVisible(false);
        kiralamaPaneli.setVisible(false);
        isletmeKurmaPaneli.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        baslangicPaneli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        isletmeKurmaPaneli = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        isletmeTuruComboBox = new javax.swing.JComboBox<>();
        isletmeTuruSecmeButonu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        arsaSatirComboBox = new javax.swing.JComboBox<>();
        arsaSutunComboBox = new javax.swing.JComboBox<>();
        arsaAlaniSec = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        satinAlmaPaneli = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        kiralamaPaneli = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baslangicPaneli.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setText("LUTFEN İŞLEM YAPMAK İSTEDİĞİNİZ BUTONA TIKLAYINIZ");

        jButton1.setText("SATIN ALMA İŞLEMLERİ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("KİRALAMA İŞLEMLERİ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("İŞLETME KURMA İŞLEMLERİ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baslangicPaneliLayout = new javax.swing.GroupLayout(baslangicPaneli);
        baslangicPaneli.setLayout(baslangicPaneliLayout);
        baslangicPaneliLayout.setHorizontalGroup(
            baslangicPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baslangicPaneliLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
            .addGroup(baslangicPaneliLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(baslangicPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        baslangicPaneliLayout.setVerticalGroup(
            baslangicPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baslangicPaneliLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jLayeredPane1.add(baslangicPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 510));

        isletmeKurmaPaneli.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("İŞLETME KURMA İŞLEMLERİNE HOŞGELDİNİZ");

        jButton2.setText("ARSA SEÇ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("ÖDEME YAP");

        isletmeTuruComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAĞAZA", "MARKET", "EMLAKÇI" }));
        isletmeTuruComboBox.setToolTipText("");

        isletmeTuruSecmeButonu.setText("SEÇ");
        isletmeTuruSecmeButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isletmeTuruSecmeButonuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setText("Kurmak istediğiniz işletme türünü seçiniz");

        arsaSatirComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        arsaSutunComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));

        arsaAlaniSec.setText("SEÇ");
        arsaAlaniSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsaAlaniSecActionPerformed(evt);
            }
        });

        jLabel6.setText("Satır");

        jLabel7.setText("Sütun");

        jLabel8.setText("ARSAYI SEÇ");

        javax.swing.GroupLayout isletmeKurmaPaneliLayout = new javax.swing.GroupLayout(isletmeKurmaPaneli);
        isletmeKurmaPaneli.setLayout(isletmeKurmaPaneliLayout);
        isletmeKurmaPaneliLayout.setHorizontalGroup(
            isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isletmeKurmaPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isletmeKurmaPaneliLayout.createSequentialGroup()
                .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isletmeTuruComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isletmeTuruSecmeButonu)))
                .addGap(28, 28, 28))
            .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2))
                    .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                        .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(arsaSatirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(arsaSutunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(arsaAlaniSec))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        isletmeKurmaPaneliLayout.setVerticalGroup(
            isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isletmeKurmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isletmeTuruComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isletmeTuruSecmeButonu)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arsaSatirComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsaSutunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsaAlaniSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(isletmeKurmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addGap(37, 37, 37))
        );

        jLayeredPane1.add(isletmeKurmaPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 340, 240));

        satinAlmaPaneli.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SATIN ALMA EKRANI");

        jButton7.setText("ARSA SATIN AL");

        jButton8.setText("MARKET SATIN AL");

        jButton9.setText("MAĞAZA SATIN AL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout satinAlmaPaneliLayout = new javax.swing.GroupLayout(satinAlmaPaneli);
        satinAlmaPaneli.setLayout(satinAlmaPaneliLayout);
        satinAlmaPaneliLayout.setHorizontalGroup(
            satinAlmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, satinAlmaPaneliLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(satinAlmaPaneliLayout.createSequentialGroup()
                .addGroup(satinAlmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(satinAlmaPaneliLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton7))
                    .addGroup(satinAlmaPaneliLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(satinAlmaPaneliLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        satinAlmaPaneliLayout.setVerticalGroup(
            satinAlmaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(satinAlmaPaneliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLayeredPane1.add(satinAlmaPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 340, 140));

        kiralamaPaneli.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Kiralama Ekranı");

        jButton10.setText("ARSA KİRALA");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("MARKET KİRALA");

        jButton12.setText("MAĞAZA KİRALA");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kiralamaPaneliLayout = new javax.swing.GroupLayout(kiralamaPaneli);
        kiralamaPaneli.setLayout(kiralamaPaneliLayout);
        kiralamaPaneliLayout.setHorizontalGroup(
            kiralamaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(kiralamaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(102, 102, 102))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kiralamaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralamaPaneliLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(121, 121, 121))))
        );
        kiralamaPaneliLayout.setVerticalGroup(
            kiralamaPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiralamaPaneliLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(kiralamaPaneli, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 340, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    kiralamaPaneli.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      satinAlmaPaneli.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       isletmeKurmaPaneli.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      //  OyunEkrani.getWindows();
        //girisEkrani giris=new girisEkrani();
       if( kurulacakIsletmeTuruBelirlendi==1){
           
        girisEkrani.oyunEkrani.arsaSecmeBelirteci=1;
        girisEkrani.oyunEkrani.setVisible(true); 
       }
       else{
           JOptionPane.showMessageDialog(null, "LÜTFEN KURMAK İSTEDİĞİNİZ İŞLETME TÜRÜNÜ SEÇİNİZ !!!");
       }
       // girisEkrani.;       // OyunEkrani.getFrames();
        //OyunEkrani oyunEkrani=new OyunEkrani();
       // oyunEkrani.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void isletmeTuruSecmeButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isletmeTuruSecmeButonuActionPerformed
   
     int secilen=isletmeTuruComboBox.getSelectedIndex();
           JOptionPane.showMessageDialog(null, "seçilen işletme:"+secilen);   
       if(secilen==0){
           girisEkrani.oyunEkrani.secilenIsletmeTuru=2;
       }
      else if(secilen==1){
           girisEkrani.oyunEkrani.secilenIsletmeTuru=3;
       }
      else if(secilen==2){
           girisEkrani.oyunEkrani.secilenIsletmeTuru=1;
       }
       kurulacakIsletmeTuruBelirlendi=1;
    }//GEN-LAST:event_isletmeTuruSecmeButonuActionPerformed

    private void arsaAlaniSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsaAlaniSecActionPerformed
      int secilenSatir=arsaSatirComboBox.getSelectedIndex();
      int secilenSutun=arsaSutunComboBox.getSelectedIndex();
      if( girisEkrani.oyunEkrani.oyunAlani[secilenSatir][secilenSutun]==0){
          JOptionPane.showMessageDialog(null, "Seçiminiz başarıyla alınmıştır !!!");//bakiye yeterliyse satın alabilsin
          //fonksiyon yaz ve ya yeni ekran aaç burası için 
           girisEkrani.oyunEkrani.oyunAlani[secilenSatir][secilenSutun]=girisEkrani.oyunEkrani.secilenIsletmeTuru;
           
      }
      else{
          JOptionPane.showMessageDialog(null, "Lütfen boş bir arsa seçiniz !!!");
      }
    
   for(int a=0;a<4;a++){
            for(int b=0;b<4;b++){
                System.out.print(girisEkrani.oyunEkrani.oyunAlani[a][b]);
                //System.out.println("slaak");
            }
            System.out.println();
        }
    }//GEN-LAST:event_arsaAlaniSecActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmlakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmlakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmlakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmlakEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmlakEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arsaAlaniSec;
    private javax.swing.JComboBox<String> arsaSatirComboBox;
    private javax.swing.JComboBox<String> arsaSutunComboBox;
    private javax.swing.JPanel baslangicPaneli;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel isletmeKurmaPaneli;
    private javax.swing.JComboBox<String> isletmeTuruComboBox;
    private javax.swing.JButton isletmeTuruSecmeButonu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel kiralamaPaneli;
    private javax.swing.JPanel satinAlmaPaneli;
    // End of variables declaration//GEN-END:variables
}
