/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaland;
import java.sql.*;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static metaland.girisEkrani.kullanici_no;
import static metaland.girisEkrani.sifre;

/**
 *
 * @author Orhan UZEL
 */
public class MagazaEkrani extends javax.swing.JFrame {

    /**
     * Creates new form MagazaEkrani
     */
    public MagazaEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MagazaEkraniPaneli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MagazaEkraniPaneli.setBackground(new java.awt.Color(255, 102, 102));
        MagazaEkraniPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAĞAZAMIZA HOŞGELDİNİZ");
        MagazaEkraniPaneli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 182, 59));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_coat_96px_1.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 81));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_flip_flops_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 81));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_men's_pajama_160px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 23, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_scarf_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 81));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_socks_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, 81));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_shirt_80px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, 81));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_tie_64px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 156));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trainers_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, 81));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_lab_coat_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 81));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_basketball_jersey_80px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 23, -1, 81));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_red_purse_48px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 81));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_womens_shirt_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_skirt_96px.png"))); // NOI18N
        MagazaEkraniPaneli.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, 81));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Mağazada Çalış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MagazaEkraniPaneli.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 220, 60));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Alışveriş Yap");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MagazaEkraniPaneli.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MagazaEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MagazaEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String sql_sorgum = "select count(id) as giris from kullanici_bilgileri where kullanici_no='"+kullanici_no+
						"' and kullanici_sifre='"+sifre+"'";
				String sql_sorgu = "select count(id) as giris from kullanici where kullanici_adi='"+kullanici_no+
						"' and sifre='"+sifre+"'";
                                String sql_sorgus = "select count(yeterid) as giris from yeter where ad='"+kullanici_no+
						"' and soyad='"+sifre+"'";
				String bilgiTutmaSorgum="SELECT  * FROM kullanici_bilgileri WHERE kullanici_no ='"+kullanici_no+
                                        "'and kullanici_sifre='"+sifre+"'";
                 /*
                                
                                INSERT INTO public."Kullanici_calisma_bilgileri" (
kullanici_calisma_baslangici, kullanici_calisma_bitisi, kullanici_calisma_gun_sayisi, kullanici_calisma_saatleri, kullanici_id) VALUES (
'21.11.2001'::timestamp without time zone, '22.11.2001'::timestamp without time zone, '5'::smallint, '4'::smallint, '2'::smallint)
 returning id;
                                
                                
                                */    
         /*        
        String zamanSorgum="INSER INTO kullanici_calisma_bilgileri values (?,?,?,?,?,?)";                        
           ResultSet kullanici_bilgilerim2 = veritabani.yap();
			 kullanici_bilgilerim2 = veritabani.sorgula(bilgiTutmaSorgum);//resultset üst taraftaydı                     
        try {
            PreparedStatement ps=veritabani.conn.prepareStatement(zamanSorgum);
            ps.setString(2, );
        
        } catch (SQLException ex) {
            Logger.getLogger(MagazaEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
       */
         CalismaEkrani calismaEkrani=new CalismaEkrani();     
         calismaEkrani.setVisible(true);
                                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       MagazaAlisverisEkrani alisVeris=new MagazaAlisverisEkrani();
       alisVeris.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagazaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagazaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagazaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagazaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagazaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MagazaEkraniPaneli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
