/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaland;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static metaland.girisEkrani.kullanici_bas_esya;
import static metaland.girisEkrani.kullanici_bas_para;
import static metaland.girisEkrani.kullanici_bas_yemek;
import static metaland.girisEkrani.kullanici_no;
import static metaland.girisEkrani.oyunEkrani;
import static metaland.girisEkrani.sifre;

/**
 *
 * @author Orhan UZEL
 */
public class MagazaAlisverisEkrani extends javax.swing.JFrame {

public void ekrandaBaslangicKalanBilgisiGosterFonk(int  basYemek,int basPara,int basEsya) {
     String strbasYemek=String.valueOf(basYemek);
     String strbasPara=String.valueOf(basPara);
     String strbasEsya=String.valueOf(basEsya);
    
    labelKalanEsya.setText(strbasEsya);
    labelKalanPara.setText(strbasPara);
    labelKalanYemek.setText( strbasYemek);
    
}
    public MagazaAlisverisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelKalanYemek = new javax.swing.JLabel();
        labelKalanPara = new javax.swing.JLabel();
        labelKalanEsya = new javax.swing.JLabel();
        buttonSatinAl = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioButtonDonat = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        radioButtonPatates = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        radioButtonEt = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        radioButtonPizza = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioButtonSosisli = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        radioButtonKarpuz = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKalanYemek.setText("yiyecek");
        jPanel1.add(labelKalanYemek, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        labelKalanPara.setText("para");
        jPanel1.add(labelKalanPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        labelKalanEsya.setText("eşya");
        jPanel1.add(labelKalanEsya, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        buttonSatinAl.setBackground(new java.awt.Color(255, 255, 51));
        buttonSatinAl.setText("SATIN AL");
        buttonSatinAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSatinAlActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSatinAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel8.setText("Lütfen Satın Almak İstediğiniz Eşyayı Seçiniz");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 260, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel14.setText("15 Esya Puanı Kazanımı");

        jLabel13.setText("Ücret=10 TL");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_socks_96px.png"))); // NOI18N

        radioButtonDonat.setText("Çorap");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addComponent(radioButtonDonat)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(radioButtonDonat)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 460, 90));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_jacket_80px.png"))); // NOI18N

        jLabel15.setText("25 Eşya Puanı Kazanımı");

        jLabel19.setText("Ücret=15 TL");

        radioButtonPatates.setText("Ceket");
        radioButtonPatates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPatatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(radioButtonPatates)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radioButtonPatates)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 460, 80));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_flip_flops_96px.png"))); // NOI18N

        jLabel20.setText("Ücret=15 TL");

        jLabel16.setText("15 Eşya Puanı Kazanımı");

        radioButtonEt.setText("Terlik");
        radioButtonEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonEtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(radioButtonEt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(radioButtonEt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 460, 70));

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_red_purse_48px.png"))); // NOI18N

        jLabel17.setText("25 Eşya Puanı Kazanımı");

        jLabel21.setText("Ücret=20 TL");

        radioButtonPizza.setText("Çanta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(radioButtonPizza)
                        .addGap(66, 66, 66))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radioButtonPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel17)
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 460, 90));

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_skirt_96px.png"))); // NOI18N

        jLabel22.setText("Ücret=18 TL");

        jLabel18.setText("30 Eşya Puanı Kazanımı");

        radioButtonSosisli.setText("Etek");
        radioButtonSosisli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSosisliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 192, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioButtonSosisli)
                        .addGap(70, 70, 70))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioButtonSosisli)
                .addGap(1, 1, 1)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 460, 70));

        jPanel7.setBackground(new java.awt.Color(51, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trainers_96px.png"))); // NOI18N

        jLabel11.setText("Ücret=30 TL");

        jLabel12.setText("60 Eşya Puanı Kazanımı");

        radioButtonKarpuz.setText("Spor Ayakkabı");
        radioButtonKarpuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonKarpuzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(radioButtonKarpuz)
                .addGap(17, 17, 17))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(radioButtonKarpuz)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 460, 80));

        jLabel1.setText("Yemek Miktarı:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel2.setText("Para Miktarı:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 70, -1));

        jLabel3.setText("Eşya Miktarı:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 70, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSatinAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSatinAlActionPerformed
        int harcananPara=0;
        int kazanilanEsya=0;
        if(radioButtonDonat.isSelected()){
            harcananPara= harcananPara+10;
            kazanilanEsya=kazanilanEsya+15;
        }
        if(radioButtonPatates.isSelected()){
            harcananPara= harcananPara+15;
            kazanilanEsya=kazanilanEsya+25;
        }
        if(radioButtonEt.isSelected()){
            harcananPara= harcananPara+15;
            kazanilanEsya=kazanilanEsya+15;
        }
        if(radioButtonPizza.isSelected()){
            harcananPara= harcananPara+20;
            kazanilanEsya=kazanilanEsya+25;
        }
        if(radioButtonSosisli.isSelected()){
            harcananPara= harcananPara+18;
            kazanilanEsya=kazanilanEsya+30;
        }

        if(radioButtonKarpuz.isSelected()){
            harcananPara= harcananPara+30;
            kazanilanEsya=kazanilanEsya+60;
        }
        JOptionPane.showMessageDialog(rootPane,"Harcan Para Miktarı: "+harcananPara+" Kazanılan Eşya Miktarı: "+kazanilanEsya);
        String bilgiTutmaSorgum="SELECT  * FROM kullanici_bilgileri WHERE kullanici_no ='"+kullanici_no+
                                        "'and kullanici_sifre='"+sifre+"'";
        int  kullanici_kalan_para;
         int   kullanici_kalan_esya;
         int   kullanici_kalan_yemek;
         int kullanici_id;
         ResultSet bilgiAl = veritabani.yap();
			 bilgiAl = veritabani.sorgula(bilgiTutmaSorgum);//resultset üst taraftaydı
               //          PreparedStatament ps=veritabani.conn.prepareStatement(bilgiTutmaSorgum);
      try {
					while(bilgiAl.next()){
                                        //    belirtec=1;
                                       //   kullanici_ad=kullanici_bilgilerim2.getString("kullanici_ad");
                                         //     kullanici_soyad=kullanici_bilgilerim2.getString("kullanici_soyad");
                                          //   kullanici_id= kullanici_bilgilerim2.getInt("id");
                                             
                                         //    kullanici_ad= kullanici_bilgilerim2.getString("kullanici_ad");
                                         //    kullanici_ad=kullanici_ad.toUpperCase();
                                         //    kullanici_soyad=kullanici_soyad.toUpperCase();
                                         kullanici_id=bilgiAl.getInt("id");
                                           kullanici_kalan_para=bilgiAl.getInt("kullanici_para_miktari");
                                            kullanici_kalan_esya=bilgiAl.getInt("kullanici_esya_miktari");
                                            kullanici_kalan_yemek=bilgiAl.getInt("kullanici_yemek_miktari");
                                          //   kullanici_bas_esya=kullanici_bilgilerim2.getInt("kullanici_esya_miktari");
                                          //   kullanici_bas_yemek=kullanici_bilgilerim2.getInt("kullanici_yemek_miktari");
                                             ekrandaBaslangicKalanBilgisiGosterFonk(kullanici_kalan_yemek, kullanici_kalan_para, kullanici_kalan_esya);
                                            String query = "update kullanici_bilgileri set kullanici_para_miktari = ?,kullanici_esya_miktari=?,kullanici_yemek_miktari=? where id ='"+kullanici_id+"'";
                                             veritabani.guncellemeFonk(query, kullanici_kalan_yemek, kullanici_kalan_esya, kullanici_kalan_para,harcananPara,kazanilanEsya,0);
//  JOptionPane.showMessageDialog(null, "GIRIS BASARILI");
                                          //    oyunEkrani.ekrandaKullaniciBilgisiGosterFonk(kullanici_ad,kullanici_soyad,kullanici_id);
                                          //    oyunEkrani.idAl(kullanici_id);
                                          //   oyunEkrani.idm=kullanici_id;
                                            //  oyunEkrani.setVisible(true);
                                        }}
      catch (SQLException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
    }//GEN-LAST:event_buttonSatinAlActionPerformed

    private void radioButtonEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonEtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonEtActionPerformed

    private void radioButtonKarpuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonKarpuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonKarpuzActionPerformed

    private void radioButtonSosisliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSosisliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonSosisliActionPerformed

    private void radioButtonPatatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPatatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonPatatesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagazaAlisverisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagazaAlisverisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagazaAlisverisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagazaAlisverisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagazaAlisverisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSatinAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelKalanEsya;
    private javax.swing.JLabel labelKalanPara;
    private javax.swing.JLabel labelKalanYemek;
    private javax.swing.JRadioButton radioButtonDonat;
    private javax.swing.JRadioButton radioButtonEt;
    private javax.swing.JRadioButton radioButtonKarpuz;
    private javax.swing.JRadioButton radioButtonPatates;
    private javax.swing.JRadioButton radioButtonPizza;
    private javax.swing.JRadioButton radioButtonSosisli;
    // End of variables declaration//GEN-END:variables
}
