/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metaland;

/**
 *
 * @author Orhan UZEL
 */
public class MarketEkrani extends javax.swing.JFrame {

    /**
     * Creates new form MarketEkrani
     */
    public MarketEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarketEkraniPaneli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MarketEkraniPaneli.setBackground(new java.awt.Color(102, 255, 102));
        MarketEkraniPaneli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARKETİMİZE HOŞGELDİNİZ");
        MarketEkraniPaneli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 182, 59));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_lemon_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 81));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_hot_dog_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 81));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_bread_96px_1.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cheese_wedge_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, 81));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_eggplant_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, 81));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cupcake_emoji_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, 81));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_french_fries_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, 156));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_doughnut_emoji_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, 81));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_gingerbread_man_128px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_pizza_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 81));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_slice_of_watermelon_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 81));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_corn_96px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_fish_food_200px.png"))); // NOI18N
        MarketEkraniPaneli.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, 110));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Markette Çalış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MarketEkraniPaneli.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 220, 60));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Alışveriş Yap");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MarketEkraniPaneli.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MarketEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MarketEkraniPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CalismaEkrani calis=new CalismaEkrani();
        calis.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    MarketAlisverisiEkrani marketAlisverisiEkrani=new MarketAlisverisiEkrani();
    marketAlisverisiEkrani.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MarketEkraniPaneli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
